### ISSUE TITLE
Compatible to 1.7

### ISSUE THREAD

**Issue by enexusde** [micromata/ConfluenceRestClient#1]
Code is not compatible to 1.7, can not be used in old applications.

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.915 s
[INFO] Finished at: 2017-12-29T12:57:13+01:00
[INFO] Final Memory: 35M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-bytecode-version) on project xxxx: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by mrkoenigstein** [comment]
Hello, 
Java 1.7 is out of public support since April'15, so if you want to have the client compatible to 1.7 then make a fork and change everything necessary.
